server:
  port: 9199

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liuWCS0XPAh9Kkrv
            client-secret: 3ee27619d3109f4ba7470705d5e60da25487f94f
