server:
  port: 9099

spring:
  security:
    oauth2:
      client:
        provider:
          microservicio-realm:
            issuer-uri: http://localhost:8080/realms/Microservicio-Realm
        registration:
          microservicio-realm:
            provider: Microservicio-Realm
            client-name: microservicio-client
            client-id: microservicio-client
            client-secret: jY2cZ8Aks6PMdYbllO2iEjqxMjbTiOx1
            scope: openid
            authorization-grant-type: authorization_code
