server:
  port: ${CUSTOM.SERVER.PORT:9080}

resilience4j:
  circuitbreaker:
    configs:
      product-service-cb:
        slidingWindowSize: 12
        failureRateThreshold: 48
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 8
        slowCallRateThreshold: 58
        slowCallDurationThreshold: 500ms
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      mitocode-product: 
        base-config: product-service-cb

# Spring Cloud Gateway Routes
spring:
  cloud:
    gateway:
      routes:

        - id: product-service-route
          uri: lb://product-service #http://service-1.com, http://service-2.com
          predicates:
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2
            - AddRequestParameter=flag,true
            - name: CircuitBreaker
              args:
                name: mitocode-product
                statusCodes: 400,401,403,500,503
                fallbackUri: forward:/api/user-service/api/mitocode/user

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
            #- name: CustomFilter
            #  args:
            #    headerKey: MitocodeKey
            #    headerValue: MitocodeValue
            - UserServiceFilter=MitocodeKey,MitocodeValue
microservicio:
  security:
    key: 7a4dd54a8f70783702831cb6b09cc8006d0c444e776365a50e9c68dd3c31438bf5929970236e251ec4fb092522f4c71c
